name: build

on:
  push:
    branches: main

  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.19]
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - name: Build CLI
        run: make build-linux-amd64
      - name: Start Distribution
        run: |
          docker stop oras-e2e || true
          docker run -d -p 5000:5000 --rm --name oras-e2e \
            --mount type=bind,source=$(pwd)/test/e2e/testdata/config-example-with-extensions.yml,target=/etc/docker/registry/config.yml \
            --mount type=bind,source=$(pwd)/test/e2e/testdata/passwd_bcrypt,target=/etc/docker/registry/passwd \
            ghcr.io/oras-project/registry:latest
      - name: Run Tests
        run: |
          trap docker stop oras-e2e || true ERR
          make test
          docker stop oras-e2e || true
        env: 
          ORAS_PATH: ${GITHUB_WORKSPACE}/bin/linux/amd64/oras
          ORAS_REGISTRY_HOST: localhost:5000
      - name: Check Version
        run: bin/linux/amd64/oras version
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v3
